language: ruby
rvm:
  - 2.5.1

services:
  - postgresql

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

deploy:
  api_key:
    secure: lJjIAn8M1pdyb1zjMTE/2WIqiNUxXjdaNEaGysKiluZMo+HvuUFC5EDtVa/e2I1uK/+Qys2wY6DwU+CWaAVFYtk6qOWj9SLZprbXSrZDUooLnHCFeguHhFN7df8XK1xTYbxPmPki6oHjvXHMqLsldAUC2XUB1OIPae8ULWTlh5jEXE5ITe0ElrKGNIaIGRfitesuecFm4DjuuzQTt4IiIYmG/TxRaUdJxcpVpzX5mAygWPA2erEEOYVelzuEXbCIs5MfS/9wwggtvohfc1iQsY0HqtIGn8I2KZs+jiou2Mv+xTw4yPPfPKDTLYdYoDLW3DHwErV3SjvYAQkuOp/9MavnqLpkPqhyigT5lhlO9/LIc7PkGNRxPmKq0TJh7fD5c27UG5uPgT8eV+Bm6Mn7ZO49sfz59hoKQAJbYEufT1+KJf0fzUA9rxJNL+BcBSjEYzP/j9bc/lYjqiRFw8SBy54exxF49YZclax+27YXHLkXohWm+jhNzKHfRyK1Bx1iEYesd/udCv5k0u9TYlfLBLoXOencqWHGJ/hvXTYE3A7Js+myH7Q662TbgpM6S0TYrJbknXloSiBPSlomgWRT8zeGxZuPW+7PzzQvp5eetMTqYhocln62gOOwY42m6W/X24Zow57v7ItC2R0eSlFXeMU/RnkWTX7APhXrio3d1Yo=
